### ISSUE TITLE
Integrate static graphs to our display page

### ISSUE THREAD

**Issue by elliot-mb** [spe-uob/2022-RouteZeroCarbonSavings#63]
https://www.chartjs.org/ Using this library with the react app in order to acquire the tools needed to display the data produced by the backend effectively, in accordance with the MVP, by December. https://files.slack.com/files-pri/T0467FTHTUL-F0477LBPY90/screenshot.png

**Comment by camillemolina1** [comment]
Starting styling view page and made an initial attempt at creating graphs
